name: musl-cross-make
base: core20
version: "1.0.0"
grade: devel
summary: musl-cross-make - as a snap
description: |-
  musl-cross-make as a snap, without having to compile it every time to install
  it.
contact: stickupkid@gmail.com
issues: https://github.com/SimonRichardson/musl-cross-make-snap/issues
source-code: https://github.com/SimonRichardson/musl-cross-make-snap
website: https://github.com/richfelker/musl-cross-make
confinement: classic

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  x86-64-linux-musl:
    command: bin/x86_64-linux-musl-gcc
  aarch64-linux-musl:
    command: bin/aarch64-linux-musl-gcc
  ppcc64le-linux-musl:
    command: bin/powerpc64le-linux-musl-gcc
  s390x-linux-musl:
    command: bin/s390x-linux-musl-gcc

parts:
  x86-64-linux-musl:
    source: https://github.com/richfelker/musl-cross-make.git
    source-type: git
    plugin: make
    build-packages:
      - gcc
      - make
      - build-essential
      - wget
      - curl
    override-build: |
      set -ex

      cat << EOF > config.mak
      TARGET = x86_64-linux-musl
      OUTPUT = $SNAPCRAFT_PART_BUILD

      COMMON_CONFIG += CFLAGS="-g0 -Os"
      COMMON_CONFIG += CXXFLAGS="-g0 -Os"
      COMMON_CONFIG += LDFLAGS="-s"
      COMMON_CONFIG += --disable-nls
      EOF

      make install

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r $SNAPCRAFT_PART_BUILD/bin $SNAPCRAFT_PART_INSTALL

  aarch64-linux-musl:
    source: https://github.com/richfelker/musl-cross-make.git
    source-type: git
    plugin: make
    build-packages:
      - gcc
      - make
      - build-essential
      - wget
      - curl
    override-build: |
      set -ex

      cat << EOF > config.mak
      TARGET = aarch64-linux-musl
      OUTPUT = $SNAPCRAFT_PART_BUILD

      COMMON_CONFIG += CFLAGS="-g0 -Os"
      COMMON_CONFIG += CXXFLAGS="-g0 -Os"
      COMMON_CONFIG += LDFLAGS="-s"
      COMMON_CONFIG += --disable-nls
      EOF

      make install

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r $SNAPCRAFT_PART_BUILD/bin $SNAPCRAFT_PART_INSTALL

  ppc64le-linux-musl:
    source: https://github.com/richfelker/musl-cross-make.git
    source-type: git
    plugin: make
    build-packages:
      - gcc
      - make
      - build-essential
      - wget
      - curl
    override-build: |
      set -ex

      cat << EOF > config.mak
      TARGET = powerpc64le-linux-musl
      OUTPUT = $SNAPCRAFT_PART_BUILD

      COMMON_CONFIG += CFLAGS="-g0 -Os"
      COMMON_CONFIG += CXXFLAGS="-g0 -Os"
      COMMON_CONFIG += LDFLAGS="-s"
      COMMON_CONFIG += --disable-nls
      EOF

      make install

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r $SNAPCRAFT_PART_BUILD/bin $SNAPCRAFT_PART_INSTALL

  s390x-linux-musl:
    source: https://github.com/richfelker/musl-cross-make.git
    source-type: git
    plugin: make
    build-packages:
      - gcc
      - make
      - build-essential
      - wget
      - curl
    override-build: |
      set -ex

      cat << EOF > config.mak
      TARGET = s390x-linux-musl
      OUTPUT = $SNAPCRAFT_PART_BUILD

      COMMON_CONFIG += CFLAGS="-g0 -Os"
      COMMON_CONFIG += CXXFLAGS="-g0 -Os"
      COMMON_CONFIG += LDFLAGS="-s"
      COMMON_CONFIG += --disable-nls
      EOF

      make install

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r $SNAPCRAFT_PART_BUILD/bin $SNAPCRAFT_PART_INSTALL
