name: musl-cross-make
base: core20
version: "1.0.0"
grade: devel
summary: musl-cross-make - as a snap
description: |-
  musl-cross-make as a snap, without having to compile it every time to install
  it.
contact: stickupkid@gmail.com
issues: https://github.com/SimonRichardson/musl-cross-make-snap/issues
source-code: https://github.com/SimonRichardson/musl-cross-make-snap
website: https://github.com/richfelker/musl-cross-make
confinement: classic

architectures:
  - build-on: amd64

apps:
  musl-gcc-x86-64:
    command: bin/x86_64-linux-musl-gcc

parts:
  bootstrap-musl-gcc:
    source: https://github.com/richfelker/musl-cross-make.git
    source-type: git
    plugin: make
    build-packages:
      - gcc
      - make
      - build-essential
      - wget
      - curl
    override-build: |
      set -ex

      cat << EOF > config.mak

      TARGET = x86_64-linux-musl
      OUTPUT = $SNAPCRAFT_PART_BUILD

      COMMON_CONFIG += CC="gcc -static --static" 
      COMMON_CONFIG += CXX="g++ -static --static"

      COMMON_CONFIG += CFLAGS="-g0 -Os"
      COMMON_CONFIG += CXXFLAGS="-g0 -Os"
      COMMON_CONFIG += LDFLAGS="-s"
      COMMON_CONFIG += --disable-nls

      GCC_CONFIG += --disable-libquadmath
      GCC_CONFIG += --disable-decimal-float
      GCC_CONFIG += --disable-libitm
      GCC_CONFIG += --disable-fixed-point
      GCC_CONFIG += --disable-lto
      EOF

      make -j$(nproc)
      make install

  musl-gcc-x86-64:
    after:
      - bootstrap-musl-gcc
    source: https://github.com/richfelker/musl-cross-make.git
    source-type: git
    plugin: make
    build-packages:
      - gcc
      - make
      - build-essential
      - wget
      - curl
    override-build: |
      set -ex

      cat << EOF > config.mak

      TARGET = x86_64-linux-musl
      OUTPUT = $SNAPCRAFT_PART_BUILD

      COMMON_CONFIG += CC="/root/parts/bootstrap-musl-gcc/build/bin/x86_64-linux-musl-gcc -static --static" 
      COMMON_CONFIG += CXX="/root/parts/bootstrap-musl-gcc/build/bin/x86_64-linux-musl-g++ -static --static"

      COMMON_CONFIG += CFLAGS="-g0 -Os"
      COMMON_CONFIG += CXXFLAGS="-g0 -Os"
      COMMON_CONFIG += LDFLAGS="-s"
      COMMON_CONFIG += --disable-nls
      EOF

      make -j$(nproc)
      make install

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r $SNAPCRAFT_PART_BUILD/bin $SNAPCRAFT_PART_INSTALL
